### Turtle graphics

In [ ]:
# design Spiral star
import turtle as t
a1 = t.Turtle()
a1.pencolor('navy blue')
for i in range(50):
    a1.forward(i * 10)
    a1.left(144)
t.done()  

In [ ]:
# design Spiral Square
import turtle as t
a1 = t.Turtle()
a1.pencolor('orange')
for i in range(150):
    a1.forward(50)
    a1.left(91)
a1.done()    


In [ ]:
# design Hexagon
from turtle import *
pencolor('blue')
colors = ['blue','green','red','navy blue','pink','purple']
for i in range(360):
    pencolor(colors[i%6])
    width(i/100 + 1)
    forward(i)
    left(70)


In [ ]:
# design circle
from turtle import *
pensize(5)
pencolor('navy blue')
fillcolor('red')
begin_fill()
circle(50) 
end_fill()


In [ ]:
# design tangent circle
from turtle import *
pensize(1)
pencolor('navy blue')
for i in range(30):
    circle(5*i)


In [ ]:
# design  spiral circle
from turtle import *
pensize(2)
pencolor('green')
for i  in range(100):
    circle(10+i,45)



In [ ]:
# design circle
from turtle import *
pensize(2)
colors = ['blue','green','red','navy blue','pink','purple']
for i in range(50):
    pencolor(colors[i%6])
    circle(10*i)
    up()
    sety((10*i)*(-1))
    down()


In [ ]:
# design olympic logo
from turtle import *
pensize(6)
r1 = ['blue','black','red']
for i in range(3):
    penup()
    pencolor(r1[i%3])
    goto(i*90,0)
    pendown()
    circle(40)
r2 = ['','yellow','','green']   
for i in range(1,4,2):
    penup()
    pencolor(r2[i])
    goto(i*45,-45)
    pendown()
    circle(40)


In [ ]:
from turtle import *
bgcolor('white')
color('#2B28F6')
fillcolor('#2B28F6')
penup()
goto(0,0)
begin_fill()
forward(570)
left(90)
forward(80)
left(90)
forward(570)
left(90)
forward(80)
end_fill()


#code for drawing the roof
pensize(6)
penup()
goto(100,50)
pendown()
setheading(45)
forward(100)
setheading(0)
forward(250)
setheading(-45)
forward(100)
setheading(90)
penup()
goto(300,50)
pendown()
forward(75)

# code for drawinf 2 tyres
penup()
goto(200,-10)
pendown()
color('black')
fillcolor('black')
begin_fill()
circle(20)
end_fill()
penup()
goto(400,-10)
pendown()
color('black')
fillcolor('black')
begin_fill()
circle(20)
end_fill()


In [ ]:
# design audi logo
from turtle import *
pensize(6)
for i in range(4):
    penup()
    goto(i*70,0)
    pendown()
    circle(50)



### idiomatic python
 - tranformation of code int0 beautiful, idiomatic python
 - replaces tranditional index manipulation with python code looping idioms 

In [2]:
# looping over a range of numbers
for i in [0,1,2,3,4,5]:
    print(i ** 2,end=' ')
    
print()    

0 1 4 9 16 25 


In [3]:
# looping over a range of numbers
for i in [0,1,2,3,4,5]:
    print(i ** 2,end=' ')
    
print()
#pythinic way
for i in range(6):
    print(i ** 2,end=' ')

0 1 4 9 16 25 
0 1 4 9 16 25 

In [6]:
# looping over the collections(list)
li = [1,2,3,4,5]
for i in range(len(li)):
    print(li[i],end=' ')
print()
#pythonic way
for i in li:
    print(i,end=' ')

1 2 3 4 5 
1 2 3 4 5 

In [7]:
# looping from backwards
li = [1,2,3,4,5]
for i in range(len(li)):
    print(li[i],end=' ')
print()
#pythonic way
for i in reversed(li):
    print(i,end=' ')

1 2 3 4 5 
5 4 3 2 1 

In [8]:
# looping from backwards
li = [1,2,3,4,5]
for i in range(len(li)-1,-1,-1):
    print(li[i],end=' ')
print()
#pythonic way
for i in reversed(li):
    print(i,end=' ')

5 4 3 2 1 
5 4 3 2 1 

In [9]:
li = [1,2,3,4,5]
for i in range(len(li)):
    print(i, '-->',li[i])
print()
#pythonic way
for i,a in enumerate(li):
    print(i, '-->',a)

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5

0 --> 1
1 --> 2
2 --> 3
3 --> 4
4 --> 5


In [12]:
#looping over two collections
li = [1,2,3,4,5]
a = [1,2,3,4,5,6,7]
n = min(len(li),len(a))
for i in range(n):
    print(li[i], ' ',a[i])
    
print()  

#pythonic way
for i,a in zip(li,a):
    print(i, ' ',a)

1   1
2   2
3   3
4   4
5   5

1   1
2   2
3   3
4   4
5   5


In [14]:
# looping in sorted order
li = [8,1,25,16,9,2]
for i in sorted(li):
    print(i,end=' ')
    
print()
for i in sorted(li,reverse=True):
    print(i,end=' ')

1 2 8 9 16 25 
25 16 9 8 2 1 

In [16]:
#Dictionary
d = {'name':'gitam','emailId':'gitam@gitam.edu','address':'vizag'}
for k in d:
    print(k,end=' ')
print()    

name emailId address 


In [17]:
for k in d.keys():
    if k.startswith('A'):
        del d[k]
print(d)        

{'name': 'gitam', 'emailId': 'gitam@gitam.edu', 'address': 'vizag'}


In [18]:
for k in d.values():
    print(k,end=' ')

gitam gitam@gitam.edu vizag 

### list comprehensions

In [20]:
li = []
for i in range(10):
    a = i** 2
    li.append(a)
    
print(sum(li))
print()

#pythonic way
sum(i**2 for i in range(10))

285



285

### Lambda Functions
 - anonymous functions means that a function is without a name
 - any lambda function on python will be defined with lambda
 - Syntax : lambda arg : expression

In [21]:
def square(n):
    return n*n
square(10)

100

In [22]:
a = lambda x : x * x
print(a(10))

100


### use of lamba with filter

In [30]:
def filterlist(li):
    a = []
    for i in li:
        if i % 2 == 0:
            a.append(i)
    return a
li = [1,2,3,4,5,6,7,8]
filterlist(li)

[2, 4, 6, 8]

In [49]:
lam_li = list(map((lambda x:x^2),range(10)))
print(lam_li)

[2, 3, 0, 1, 6, 7, 4, 5, 10, 11]


In [31]:
def squareList(li):
    a = []
    for i in li:
        a.append(i*2)
    return a
li =[1,2,3,4,5,6,7,8]
squareList(li)

[2, 4, 6, 8, 10, 12, 14, 16]

In [46]:
li = [1,2,3,4,5,6,7,8]
map_list = list(map((lambda x : x**2,filter((lambda x : x%2,range(10)))
print(map_list)

SyntaxError: invalid syntax (<ipython-input-46-2909926a1d58>, line 3)

### lambda with reduce

In [37]:
def sumlist(li):
    s = 0
    for i in li:
        s += i
    return s
li = [1,2,3,4,5,6,7,8]
sumlist(li)

36

In [38]:
from functools import reduce
li = [1,2,3,4,5,6,7,8]
s = reduce((lambda x,y:x+y),li)
print(s)

36


### Standard package
 #### pandas,numpy and matplotlib

### pandas
   #### use cases
   - data cleaning
   - data transformation
   - data analysis
 ### notations
  - series
      - a series is a one-dimensional object that can hold it
 

In [1]:
import pandas as pd
internal1 = {'s1':35,'s2':35,'s3':35}
internal1 = pd.Series(internal1)
print(internal1)

s1    35
s2    35
s3    35
dtype: int64


In [4]:
import pandas as pd
internal1 = {'s1':35,'s2':35,'s3':35}
internal2 = {'s1':45,'s2':45,'s3':45}
internal1 = pd.Series(internal1)
internal2 = pd.Series(internal2)
print(internal1)
print(internal2)

s1    35
s2    35
s3    35
dtype: int64
s1    45
s2    45
s3    45
dtype: int64


In [5]:
final = {'internal1':internal1,'internal2':internal2}
final = pd.DataFrame(final)
print(final)
print(type(final))

    internal1  internal2
s1         35         45
s2         35         45
s3         35         45
<class 'pandas.core.frame.DataFrame'>


In [6]:
final.columns

Index(['internal1', 'internal2'], dtype='object')

In [7]:
final.values

array([[35, 45],
       [35, 45],
       [35, 45]], dtype=int64)

In [8]:
final.values[1]

array([35, 45], dtype=int64)

In [12]:
final.values[2]=35

In [13]:
final.values

array([[35, 45],
       [35, 45],
       [35, 35]], dtype=int64)

In [15]:
for row in final.values:
    print('internal1 - ',row[0],'internal2 -',row[1])

internal1 -  35 internal2 - 45
internal1 -  35 internal2 - 45
internal1 -  35 internal2 - 35


In [16]:
final.loc['s4'] = [20,18]
final

internal1  internal2
s1         35         45
s2         35         45
s3         35         35
s4         20         18

In [17]:
pwd


'C:\\Users\\Admin\\Desktop\\Problem Solving'

In [28]:
filePath = 'C:\\Users\\Admin\\Desktop\\Problem Solving\\Income.csv'
def readCsvData(filePath):
    return pd.read_csv(filePath)
df = readCsvData(filePath)
print(df)

       GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528  


In [29]:
for row in df.values:
    print(row[1], ':',row[-1])
    

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [31]:
def avgofState():
    s = 0
    for i in range(2,11):
        s += df.values[4][i]
    return s //len(df.values[4][2:])
avgofState()

55350

In [35]:
def printDataFrameColumns(df):
    li = []
    columns = df.columns
    for i in columns:
        li.append(i)
    return li
printDataFrameColumns(df)

['GEOID',
 'State',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [36]:
filePath = 'C:\\Users\\Admin\\Desktop\\Problem Solving\\RegularSeasonCompactResults.csv'
def readCsvData(filePath):
    return pd.read_csv(filePath)
df = readCsvData(filePath)
print(df)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
5         1985      25   1218      79   1337      78    H      0
6         1985      25   1228      64   1226      44    N      0
7         1985      25   1242      58   1268      56    N      0
8         1985      25   1260      98   1133      80    H      0
9         1985      25   1305      97   1424      89    H      0
10        1985      25   1307     103   1288      71    H      0
11        1985      25   1344      75   1438      71    N      0
12        1985      25   1374      91   1411      72    H      0
13        1985      25   1412      70   1397      65    N      0
14        1985      25   

In [38]:
df.shape

(145289, 8)

In [39]:
df.head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [40]:
df.tail()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

In [41]:
df.columns.tolist()

['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc', 'Numot']

In [42]:
df.describe()

Season         Daynum          Wteam         Wscore  \
count  145289.000000  145289.000000  145289.000000  145289.000000   
mean     2001.574834      75.223816    1286.720646      76.600321   
std         9.233342      33.287418     104.570275      12.173033   
min      1985.000000       0.000000    1101.000000      34.000000   
25%      1994.000000      47.000000    1198.000000      68.000000   
50%      2002.000000      78.000000    1284.000000      76.000000   
75%      2010.000000     103.000000    1379.000000      84.000000   
max      2016.000000     132.000000    1464.000000     186.000000   

               Lteam         Lscore          Numot  
count  145289.000000  145289.000000  145289.000000  
mean     1282.864064      64.497009       0.044387  
std       104.829234      11.380625       0.247819  
min      1101.000000      20.000000       0.000000  
25%      1191.000000      57.000000       0.000000  
50%      1280.000000      64.000000       0.000000  
75%      1375.000000      72.000000       0.000000  
max      1464.000000     150.000000       6.000000

In [55]:
df[df['Wscore']>170]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
17867    1989      92   1258     181   1109     150    H      0
19653    1990      30   1328     173   1109     101    H      0
24341    1991      47   1328     172   1258     112    H      0
24970    1991      68   1258     186   1109     140    H      0